#!/bin/bash

# Define paths
NOTES_DIRECTORY="$HOME/Documents/Notes"
NOTES_FILE_PATH="$NOTES_DIRECTORY/main/notes.txt"
SEGREGATED_NOTES_DIR="$NOTES_DIRECTORY/sorted"
CONFIG_FILE_PATH="note_tool_config.sh"
TOOL_SCRIPT_PATH="note_tool.sh"

# Ensure main and sorted directories are created
mkdir -p "$NOTES_DIRECTORY/main" "$SEGREGATED_NOTES_DIR" "$NOTES_DIRECTORY/.bin"

# Create a README file explaining the directory structure
cat <<EOL > "$NOTES_DIRECTORY/README.txt"
Note Tool - Command Line Note-Taking Application
Author: Ravi Umadi, 2024

This is the Notes directory created for the note_tool application.

Get the tool at https://github.com/raviumadi/note_tool.git
The license information can be found in the LICENSE file. https://github.com/raviumadi/note_tool/blob/main/LICENSE.md

The note_tool is a simple and efficient command-line utility for quick note-taking, organizing, and viewing notes with optional monthly segregation. Designed to be lightweight and practical, it enables you to add timestamped notes, view them by date, and maintain an organized directory of your work history.

Perfect for terminal users, the Note Tool helps capture thoughts, track tasks, outline workflows, and organize ideas without interrupting your workflow. Notes are stored in a single file, with an option to segregate them by month, either on demand or through an automated cron job. This makes it easy to maintain a structured, digital stack of notepaper to revisit or track daily progress.

	*	main/notes.txt: Stores all notes in a single main file with timestamps.
	*	sorted/: Contains monthly segregated notes, organized by year and month.
    *   .bin/: Contains the note_tool script and configuration file. [HIDDEN]

This folder and its contents were generated by the note_tool, a command-line tool to help you quickly add, organize, and view notes. You can update the paths for these files in note_tool_config.sh if you wish to change the default locations.

For more information, see the note_tool documentation or use one of the following commands:

	•	note -a to add a new note.
	•	note -v main to view the main notes file.
	•	note -v YYYY MM to view notes for a specific year and month (e.g., note -v 2024 11).
	•	note -s to segregate notes by month.
	•	note -h to see all available commands and options.

Enjoy using note_tool for streamlined note-taking!
EOL

# Copy note_tool_config.sh and note_tool.sh to their designated locations
cp "$CONFIG_FILE_PATH" "$NOTES_DIRECTORY/.bin/note_tool_config.sh"
cp "$TOOL_SCRIPT_PATH" "$NOTES_DIRECTORY/.bin/note_tool.sh"  # Adjust the location if necessary

# Append source command to .bashrc or .zshrc if not already added
if [[ -f "$HOME/.bashrc" ]]; then
    if ! grep -Fxq "source $NOTES_DIRECTORY/.bin/note_tool_config.sh" "$HOME/.bashrc"; then
        echo "source $NOTES_DIRECTORY/.bin/note_tool_config.sh" >> "$HOME/.bashrc"
    fi
    source ~/.bashrc
    echo "Shell re-sourced"
elif [[ -f "$HOME/.zshrc" ]]; then
    if ! grep -Fxq "source $NOTES_DIRECTORY/.bin/note_tool_config.sh" "$HOME/.zshrc"; then
        echo "source $NOTES_DIRECTORY/.bin/note_tool_config.sh" >> "$HOME/.zshrc"
    fi
    source ~/.zshrc
    echo "Shell re-sourced"
fi

# Reload the shell configuration
source "$HOME/.bashrc" 2>/dev/null || source "$HOME/.zshrc" 2>/dev/null

# Inform the user that the setup is complete
echo "note_tool has been set up successfully!"
echo "The Notes directory has been created at $NOTES_DIRECTORY."
# echo "To start using the tool, open a new terminal session or run 'source ~/.bashrc' or 'source ~/.zshrc'."
echo "You can now use the 'note' command to interact with the note_tool.
echo "For more information, use 'note -h' to display the help message.
echo "Enjoy taking notes!"